# Generated by Django 6.0.4 on 2026-04-10 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('plagiarism', 'Plagiarism Detected'), ('suspicious', 'Suspicious Activity'), ('review', 'Review Update'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='matched_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revise', 'Needs Revision')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.researchpaper'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload Paper'), ('download', 'Download Paper'), ('delete', 'Delete Paper'), ('search', 'Search'), ('view', 'View Paper')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revise', 'Needs Revision')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.researchpaper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
